# Rules instruct gitleaks on what should be considered a secret.
# Allowlists instruct gitleaks on what is allowed, i.e. not a secret.

title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "global allow lists"
regexes = [
    '''(?i)^true|false|null$''',
    '''^(?i:a+|b+|c+|d+|e+|f+|g+|h+|i+|j+|k+|l+|m+|n+|o+|p+|q+|r+|s+|t+|u+|v+|w+|x+|y+|z+|\*+|\.+)$''',
    '''^\$(\d+|{\d+})$''',
    '''^\$([A-Z_]+|[a-z_]+)$''',
    '''^\${([A-Z_]+|[a-z_]+)}$''',
    '''^\{\{[ \t]*[\w ().|]+[ \t]*}}$''',
    '''^\$\{\{[ \t]*((env|github|secrets|vars)(\.[A-Za-z]\w+)+[\w "'&./=|]*)[ \t]*}}$''',
    '''^%([A-Z_]+|[a-z_]+)%$''',
    '''^%[+\-# 0]?[bcdeEfFgGoOpqstTUvxX]$''',
    '''^\{\d{0,2}}$''',
    '''^@([A-Z_]+|[a-z_]+)@$''',
]

[[rules]]
id = "generic-password"
description = "Generic password assignment"
regex = '''(?i)(password|passwd|pwd|secret)\s*[:=]\s*['"]?[A-Za-z0-9!@#$%^&*()_+\-={}\[\]:;'",.<>?]{4,}['"]?'''
tags = ["password", "secret"]

[[rules]]
id = "db-connection-string"
description = "Database connection string with credentials"
regex = '''[a-zA-Z]+:\/\/[A-Za-z0-9._%+-]+:[^@]+@[A-Za-z0-9._%+-]+(:[0-9]+)?\/[A-Za-z0-9._%+-]+'''
tags = ["db", "connection", "credentials"]