# Rules instruct gitleaks on what should be considered a secret.
# Allowlists instruct gitleaks on what is allowed, i.e. not a secret.

title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "global allow lists"
regexes = [
    '''(?i)^true|false|null$''',
    '''^(?i:a+|b+|c+|d+|e+|f+|g+|h+|i+|j+|k+|l+|m+|n+|o+|p+|q+|r+|s+|t+|u+|v+|w+|x+|y+|z+|\*+|\.+)$''',
    '''^\$(\d+|{\d+})$''',
    '''^\$([A-Z_]+|[a-z_]+)$''',
    '''^\${([A-Z_]+|[a-z_]+)}$''',
    '''^\{\{[ \t]*[\w ().|]+[ \t]*}}$''',
    '''^\$\{\{[ \t]*((env|github|secrets|vars)(\.[A-Za-z]\w+)+[\w "'&./=|]*)[ \t]*}}$''',
    '''^%([A-Z_]+|[a-z_]+)%$''',
    '''^%[+\-# 0]?[bcdeEfFgGoOpqstTUvxX]$''',
    '''^\{\d{0,2}}$''',
    '''^@([A-Z_]+|[a-z_]+)@$''',
]

#
# CUSTOM RULES
#

# 1. Password assignments
[[rules]]
id = "generic-password"
description = "Generic password assignment (hardcoded values)"
regex = '''(?i)(password|passwd|pwd|secret)\s*['"]?\s*[:=>\-]+\s*['"][A-Za-z0-9!@#$%^&*()_+\-={}\[\]:;'",.<>?]{4,}['"]'''
tags = ["password", "secret"]

# 2. Database connection strings
[[rules]]
id = "db-connection-string"
description = "Database connection string with credentials"
regex = '''[a-zA-Z]+:\/\/[A-Za-z0-9._%+-]+:[^@]+@[A-Za-z0-9._%+-]+(:[0-9]+)?\/[A-Za-z0-9._%+-]+'''
tags = ["db", "connection", "credentials"]

# 3. Hardcoded JWT tokens
[[rules]]
id = "jwt-token"
description = "Hardcoded JWT token"
regex = '''eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9._-]{10,}\.[A-Za-z0-9._-]{10,}'''
tags = ["jwt", "token"]

# 4. Private key blocks
[[rules]]
id = "private-key"
description = "Private key material"
regex = '''-----BEGIN (EC|RSA|DSA|PGP|OPENSSH) PRIVATE KEY-----'''
tags = ["key", "private"]

# 5. API keys in JS/TS/PHP
# [[rules]]
# id = "api-key-assignment"
# description = "Generic API key pattern (frontend/backend)"
# regex = '''(?i)(api[_-]?key|client[_-]?secret|auth[_-]?token)\s*[:=]\s*['"][A-Za-z0-9_\-]{12,}['"]'''
# tags = ["api", "key", "secret"]

# 6. Email with password nearby (common in Laravel seeds / tests)
[[rules]]
id = "email-password-pair"
description = "Email + password combo in code"
regex = '''[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\s*[,;:\t ]+\s*['"]?[A-Za-z0-9!@#$%^&*()_+]{6,}['"]?'''
tags = ["email", "password"]